apiVersion: training.educates.dev/v1beta1
kind: TrainingPortal
metadata:
  name: bootiful-kubernetes-operators
spec:
  portal:
    sessions:
      maximum: 8
  workshops:
  - name: bootiful-kubernetes-operators
    capacity: 5
    expires: 2h
    orphaned: 1h
    reserved: 0
