apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: bootiful-kubernetes-operators
spec:
  title: Bootiful Kubernetes Operators
  description: TODO
  workshop:
    container: ghcr.io/vmware-tanzu-labs/educates-base-environment:2.5.2
    files:
    - git:
        url: https://github.com/tiffanyfay/bootiful-kubernetes-operators-workshop
        ref: origin/main
      includePaths:
      - /workshop/**
  session:
    namespaces:
      budget: small
    applications:
      console:
        enabled: true
      editor:
        enabled: true
