apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: bootiful-kubernetes-operators
spec:
  title: Bootiful Kubernetes Operators
  description: A workshop that demonstrates how to build Kubernetes operators with Spring Boot.
  workshop:
    image: ghcr.io/tiffanyfay/bootiful-kubernetes-operators-workshop:main 
    files:
    - git:
        url: https://github.com/tiffanyfay/bootiful-kubernetes-operators-workshop
        ref: origin/main
      includePaths:
      - /workshop/**
      - /samples/**
  session:
    resources:
      memory: 10Gi
    namespaces:
      budget: custom
      security:
        policy: baseline
    applications:
      console:
        enabled: true
      editor:
        enabled: true
      terminal:
        enabled: true
        layout: split
      docker:
        enabled: true
        storage: 10Gi
      registry:
        enabled: true
      vcluster:
        enabled: true
        ingress:
          enabled: true
        objects:
        - apiVersion: v1
          kind: Secret
          type: kubernetes.io/service-account-token
          metadata:
            name: default-sa-token
            namespace: default
            annotations:
              kubernetes.io/service-account.name: "default"
    ingresses:
    - name: my-first-foo
      host: my-first-foo-x-default-x-my-vcluster.$(session_namespace)
      port: 80