apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: bootiful-kubernetes-operators
spec:
  title: Bootiful Kubernetes Operators
  description: A workshop that demonstrates how to build Kubernetes operators with Spring Boot.
  workshop:
    image: ghcr.io/vmware-tanzu-labs/educates-jdk17-environment:2.5.2
    files:
    - git:
        url: https://github.com/tiffanyfay/bootiful-kubernetes-operators-workshop
        ref: origin/main
  session:
    namespaces:
      budget: small
      security:
        policy: restricted
    applications:
      console:
        enabled: true
      editor:
        enabled: true
      terminal:
        enabled: true
        layout: split
      vcluster:
        enabled: true
        ingress:
          enabled: true