apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: bootiful-kubernetes-operators
spec:
  title: Markdown Sample
  description: A sample workshop using Markdown
  workshop:
    files:
    - git:
        url: https://github.com/tiffanyfay/bootiful-kubernetes-operators-workshop
        ref: origin/main
      includePaths:
      - /workshop/**
  session:
    namespaces:
      budget: small
    applications:
      console:
        enabled: true
      editor:
        enabled: true
