piVersion: apps/v1
kind: Deployment
metadata:
  name: replace-me-name
  namespace: replace-me-namespace
spec:
  selector:
    matchLabels:
      app: replace-me-name
  replicas: 2
  template:
    metadata:
      labels:
        app: replace-me-name
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-index-file
              mountPath: /usr/share/nginx/html/
      volumes:
        - name: nginx-index-file
          configMap:
            name: replace-me-name