apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.spring.io
spec:
  group: spring.io
  names:
    kind: Foo
    plural: foos
    singular: foo
  scope: Namespaced
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                nickname:
                  description: The nickname of your Foo
                  type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
