apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.spring.io
spec:
  preserveUnknownFields: false
  group: spring.io
  names:
    kind: Foo
    listKind: FooList
    plural: foos
    singular: foo
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
#      additionalPrinterColumns:
#        - jsonPath: .spec.name
#          description: name
#          name: Foo
#          type: string
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          description: Foo is the Schema for the foo API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: FooSpec defines the desired state of Foo
              properties:
                name:
                  description: Name your foo, fool!
                  type: string
              type: object
            status:
              description: FooStatus defines the observed state of Foo
              properties:
                name:
                  type: string
              type: object
          type: object
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []