name: CRD Java Model Generate
on:
  workflow_dispatch: 
  push:
    branches: ['main']
    paths: ['samples/foo-crd.yaml']

env:
  IMAGE_NAME: ghcr.io/kubernetes-client/java/crd-model-gen
  IMAGE_TAG: v1.0.6
  GEN_DIR: crd-gen

permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run CRD Model Generation
        run: |
          LOCAL_MANIFEST_FILE=$(pwd)/samples/foo-crd.yaml
          mkdir -p ${GEN_DIR}
          docker run \
            --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$(pwd)":"$(pwd)" \
            --network host \
            ${IMAGE_NAME}:${IMAGE_TAG} \
            /generate.sh \
            -u $LOCAL_MANIFEST_FILE \
            -n foos.spring.io \
            -p io.spring.controller.models \
            -o "$(pwd)/${GEN_DIR}"
          ls -lh ${GEN_DIR}
      - uses: actions/upload-artifact@v3
        with:
          name: generated-java-crd-model
          path: |
            ${{ env.GEN_DIR }}







            mkdir -p /tmp/crds && cd /tmp/crds
wget https://gist.githubusercontent.com/yue9944882/266fee8e95c2f15a93778263633e72ed/raw/be12c13379eeed13d2532cb65da61fffb19ee3e7/crontab-crd.yaml

# Local generation
LOCAL_MANIFEST_FILE=/tmp/crds/crontab-crd.yaml
mkdir -p /tmp/java && cd /tmp/java
docker run \
  --rm \
  -v "$LOCAL_MANIFEST_FILE":"$LOCAL_MANIFEST_FILE" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "$(pwd)":"$(pwd)" \
  -ti \
  --network host \
  ghcr.io/kubernetes-client/java/crd-model-gen:v1.0.6 \
  /generate.sh \
  -u $LOCAL_MANIFEST_FILE \
  -n com.example.stable \
  -p com.example.stable \
  -o "$(pwd)"
