name: CRD Java Model Generate
on:
  workflow_dispatch: 
  push:
    branches: ['main']
    paths: ['samples/foo-crd.yaml']

env:
  IMAGE_NAME: ghcr.io/kubernetes-client/java/crd-model-gen
  IMAGE_TAG: v1.0.6
  GEN_DIR: crd-gen

permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run CRD Model Generation
        run: |
          LOCAL_MANIFEST_FILE=$(pwd)/samples/foo-crd.yaml
          mkdir -p ${GEN_DIR}
          docker run \
            --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$(pwd)":"$(pwd)" \
            --network host \
            ${IMAGE_NAME}:${IMAGE_TAG} \
            /generate.sh \
            -u $LOCAL_MANIFEST_FILE \
            -n io.spring \
            -p io.spring.controller \
            -o "$(pwd)/${GEN_DIR}"
          ls -lh ${GEN_DIR}
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.GEN_DIR }}/
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
